User Story 2 frontend complete
cse110-sp24-group28/cse110-sp24-group28-final-project pull request #20
Opened 2024-05-17 16:38 UTC by IncogOwl

- This has the front end code for both the journal and task requirements.
- We did not do a popup because we realized that people have pop-up blockers automatically installed and so it can reduce functionality.

2024-05-17 21:39 UTC, bobbymcbobboi requested changes

2024-05-17 21:39 UTC, bobbymcbobboi commented on src/index.html
> +          <button id="create" onclick="window.location.href = 'journal.html'">Create</button>
please use a js file and attach an onclick event instead of embedding javascript into the html

2024-05-17 21:39 UTC, bobbymcbobboi commented on src/journal.html
> +    <h1 style="color: rgb(0, 23, 128); font-size: 30px; margin: 0" id="dateHeader">Today</h1>
better to add a classname and style it in css file

2024-05-18 21:22 UTC, Sara0112 commented
Closed this pull request since the "Group2 backend local storage for journal and task added" pull request includes this part.

2024-05-18 21:22 UTC, closed without merging